services:
  - type: web
    name: school-management-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server-demo.js"
    envVars:
      - key: NODE_ENV
        value: production
